// ABOUTME: Compile-time expression tree metadata for clean source text display.
// ABOUTME: Generated by rewriter, walked in parallel with runtime expression tree.

namespace SharpAssert;

public record ExprNode(
    string Text,
    ExprNode? Left = null,
    ExprNode? Right = null,
    ExprNode? Operand = null,
    ExprNode[]? Arguments = null
);
