// ABOUTME: Compile-time expression tree metadata for clean source text display.
// ABOUTME: Generated by rewriter, walked in parallel with runtime expression tree.

namespace SharpAssert;

/// <summary>
/// Represents a node in the expression syntax tree, preserving original source text.
/// </summary>
/// <param name="Text">The source code text for this expression node.</param>
/// <param name="Left">The left operand for binary operations.</param>
/// <param name="Right">The right operand for binary operations.</param>
/// <param name="Operand">The operand for unary operations.</param>
/// <param name="Arguments">The argument nodes for method calls.</param>
/// <remarks>
/// <para>
/// This metadata tree is generated by the MSBuild rewriter and mirrors the structure
/// of the runtime expression tree, but preserves the original source text for each
/// node. This allows assertion failures to display exactly what you wrote in code,
/// not a reconstructed approximation.
/// </para>
/// <para>
/// The tree structure depends on the expression type:
/// - Binary operations (x > y): Both Left and Right are set
/// - Unary operations (!x): Operand is set
/// - Method calls (foo.Bar(x, y)): Arguments array is populated
/// </para>
/// <para>
/// Thread Safety: This type is immutable and thread-safe.
/// </para>
/// </remarks>
/// <example>
/// <code>
/// // For the expression "x > 10", the rewriter creates:
/// new ExprNode(
///     Text: "x > 10",
///     Left: new ExprNode("x"),
///     Right: new ExprNode("10")
/// );
/// </code>
/// </example>
public record ExprNode(
    string Text,
    ExprNode? Left = null,
    ExprNode? Right = null,
    ExprNode? Operand = null,
    ExprNode[]? Arguments = null
);
